r"""
Tests for Honeytoken Swarms and Multi-Layer Encoding Detection Engine.
Verifies decoy synthesis and detection across all 6 encoding layers:
Plaintext, URL, Base64, Hexadecimal, Homoglyphs, and Zero-Width Unicode.
"""

import base64
import urllib.parse
import pytest

from daxda_engine.level3.honeytoken_swarms import (
    HoneytokenType,
    SynthesizedHoneytoken,
    HoneytokenSynthesizer,
    EncodingLayer,
    HoneytokenDetectionHit,
    HoneytokenSwarmDetector,
)


def test_decoy_synthesizer_formats():
    r"""Verify realistic secret formats generated by decoy synthesizer."""
    synth = HoneytokenSynthesizer()

    token_aws = synth.create_honeytoken(HoneytokenType.AWS_ACCESS_KEY, context_tag="rag_aws")
    assert token_aws.raw_secret_value.startswith("AKIA")
    assert token_aws.canary_signature in token_aws.raw_secret_value.lower()

    token_db = synth.create_honeytoken(HoneytokenType.DATABASE_URL, context_tag="rag_db")
    assert token_db.raw_secret_value.startswith("postgresql://")
    assert token_db.canary_signature in token_db.raw_secret_value

    token_jwt = synth.create_honeytoken(HoneytokenType.JWT_BEARER)
    assert token_jwt.raw_secret_value.startswith("eyJhbGciOi")


def test_detection_plaintext_and_url():
    r"""Verify detection of plaintext and URL-encoded exfiltrated canaries."""
    synth = HoneytokenSynthesizer()
    token = synth.create_honeytoken(HoneytokenType.API_KEY, context_tag="api_keys")

    detector = HoneytokenSwarmDetector([token])

    # 1. Plaintext
    hits_plain = detector.scan_text(f"Exfiltrated data: {token.raw_secret_value} in prompt")
    assert len(hits_plain) == 1
    assert hits_plain[0].detected_layer == EncodingLayer.PLAINTEXT

    # 2. URL encoded
    url_payload = f"GET /leak?secret={urllib.parse.quote(token.raw_secret_value)}"
    hits_url = detector.scan_text(url_payload)
    assert len(hits_url) == 1
    assert hits_url[0].matched_canary_signature == token.canary_signature


def test_detection_base64_and_hex():
    r"""Verify detection of Base64 and Hexadecimal concealed canaries."""
    synth = HoneytokenSynthesizer()
    token = synth.create_honeytoken(HoneytokenType.AWS_ACCESS_KEY, context_tag="aws_creds")
    detector = HoneytokenSwarmDetector([token])

    # Base64 concealment
    b64_secret = base64.b64encode(token.raw_secret_value.encode()).decode()
    payload_b64 = f"User prompt containing secret blob: {b64_secret}"
    hits_b64 = detector.scan_text(payload_b64)
    assert len(hits_b64) == 1
    assert hits_b64[0].detected_layer == EncodingLayer.BASE64

    # Hexadecimal concealment
    hex_secret = token.raw_secret_value.encode().hex()
    payload_hex = f"Memory dump payload: {hex_secret}"
    hits_hex = detector.scan_text(payload_hex)
    assert len(hits_hex) == 1
    assert hits_hex[0].detected_layer == EncodingLayer.HEXADECIMAL


def test_detection_homoglyphs_and_zero_width():
    r"""Verify detection of Homoglyph-substituted and Zero-Width steganography canaries."""
    synth = HoneytokenSynthesizer()
    token = synth.create_honeytoken(HoneytokenType.API_KEY, context_tag="stego_test")
    detector = HoneytokenSwarmDetector([token])

    # Replace Latin 'a' with Cyrillic 'а' (\u0430) and 'e' with Cyrillic 'е' (\u0435)
    corrupted_homo = token.raw_secret_value.replace('a', '\u0430').replace('e', '\u0435')
    hits_homo = detector.scan_text(f"Prompt with Cyrillic homoglyphs: {corrupted_homo}")
    assert len(hits_homo) == 1
    assert hits_homo[0].matched_canary_signature == token.canary_signature

    # Intersperse zero-width spaces (\u200B) between every character
    zw_injected = "\u200B".join(list(token.raw_secret_value))
    hits_zw = detector.scan_text(f"Zero width covert string: {zw_injected}")
    assert len(hits_zw) == 1
    assert hits_zw[0].matched_canary_signature == token.canary_signature


def test_clean_text_no_false_positives():
    r"""Verify clean benign text produces zero false positive alerts."""
    synth = HoneytokenSynthesizer()
    tokens = [synth.create_honeytoken(HoneytokenType.API_KEY) for _ in range(5)]
    detector = HoneytokenSwarmDetector(tokens)

    benign_text = "The quick brown fox jumps over the lazy dog. Standard RAG vector search query."
    hits = detector.scan_text(benign_text)
    assert len(hits) == 0
