apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: da13-validator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: 8000
      protocol: TCP
      name: http-api
    - port: {{ .Values.service.metricsPort }}
      targetPort: 9090
      protocol: TCP
      name: prometheus-metrics
    - port: {{ .Values.service.websocketPort }}
      targetPort: 8765
      protocol: TCP
      name: websocket-stream
  selector:
    app.kubernetes.io/name: da13-validator
    app.kubernetes.io/component: head
